### ISSUE TITLE
Btdu freezing

### ISSUE THREAD

**Issue by AtilaSaraiva** [CyberShadow/btdu#13]
Hello,

I'm experiencing a issue with btdu freezing on my machine after a few seconds. I'm using NixOS 22.05 (I'm the maintainer of the package there), while using a lenovo ideapad 3 with a ryzen 5500U.

Best regards.

**Comment by CyberShadow** [comment]
Sounds like #12. Please try updating to v0.4.1.

**Comment by AtilaSaraiva** [comment]
Oh great, the package on the unstable channel is already at 0.4.1 but since I'm using the stable I'm still on 0.3.1. I will backport it to the stable channel then.
