### ISSUE TITLE
Can't seem to find root

### ISSUE THREAD

**Issue by bshor** [CyberShadow/btdu#14]
Hello, I must be misunderstanding something basic. I'm trying to run btdu on my system, which is a Garuda Linux (Arch derivative) distribution.

Here's the fstab entry for /. Isn't this enough to run? Instead I get the error that I'm

`UUID=.... / btrfs subvol=/@,defaults,noatime,space_cache,noautodefrag,compress-force`

Instead I get the error

`Fatal error: / is not the root btrfs subvolume`

Probably I need to temporarily mount something, but I'm not exactly sure how.

**Comment by BitBernd** [comment]
Hi, 

I just installed the tool 10 minutes ago to investigate some weird stuff going on with my btrfs.
I had no luck just using 
`sudo btdu /`
either.

So I followed the instructions and mounted my btrfs partition to a separate mount point.
On my machine this looked like this:

```
mkdir btrfs_mnt
sudo mount /dev/sdb2 btrfs_mnt/ -o subvol=/,subvolid=5 
sudo btdu btrfs_mnt/
```

It took me 5 minutes to find the problem. I wasted the entire evening yesterday on this problem trying to diagnose with standard btrfs tools. Thanks to CyberShadow for this great tool!

**Comment by CyberShadow** [comment]
@bshor btdu should print an explanation and instructions for how to mount the root subvolume along with that error message, does it not do that for you?

**Comment by bshor** [comment]
> @bshor btdu should print an explanation and instructions for how to mount the root subvolume along with that error message, does it not do that for you?

No. Only "Fatal error: / is not the root btrfs subvolume - please specify the path to a mountpoint mounted with subvol=/ or subvolid=5"

**Comment by bshor** [comment]
@BitBernd Your instructions worked perfectly. I wasn't figuring out the correct mounting instructions. Thank you!

**Comment by CyberShadow** [comment]
@bshor Your version of btdu is very old. That variation of the message has since been improved several times. In any case I suggest using the latest version of btdu. If you got that version of btdu from somewhere recently, please let me know where that is so that we can get it fixed.

**Comment by BitBernd** [comment]
When I saw this msg earlier today it was a bit longer but was not including any instructions. I got my install fresh from the AUR.

**Comment by CyberShadow** [comment]
I'm confused. Which instructions did you refer to in your previous message then? ("So I followed the instructions and [...]")

Your AUR helper may be giving you an old version. Try running `btdu` without arguments, it will print the version on the first line.

**Comment by bshor** [comment]
@CyberShadow Indeed I was using the btdu-bin package from the AUR, which was version 0.3.0. I uninstalled it and installed the normal btdu package, which is version 0.5.0.

**Comment by CyberShadow** [comment]
Thanks! I submitted a request to delete that package as it's unmaintained for some time.
