### ISSUE TITLE
Maintainer of btdu not reachable via E-Mail in the AUR, Submitted btdu-bin into the AUR due to issues on aarch64

### ISSUE THREAD

**Issue by zDEFz** [CyberShadow/btdu#16]
See title.
- Mail to Vladimir Panteleev `<arch-pkg at thecybershadow.net>`  was returned to sender.
- Submission of https://aur.archlinux.org/packages/btdu-bin was required cause cannot compile the binaries on aarch64 due to the d compilers. Not even when resolving the required packages via AUR / pacman. Specifically on the m1 mac mini running Archlinux.

**Comment by CyberShadow** [comment]
> Mail to Vladimir Panteleev `<arch-pkg at thecybershadow.net>` was returned to sender.

Odd, do you have the reason the SMTP server provided for bouncing your message?

**Comment by CyberShadow** [comment]
> * cause cannot compile the binaries on aarch64 due to the d compilers

What was the problem with that?

**Comment by zDEFz** [comment]
> > Mail to Vladimir Panteleev `<arch-pkg at thecybershadow.net>` was returned to sender.
> 
> Odd, do you have the reason the SMTP server provided for bouncing your message?

[<arch-pkg@thecybershadow.net>](mailto:arch-pkg@thecybershadow.net): TLS is required, but was not offered by host
    mail.thecybershadow.net[95.216.24.116]

^ Fix that please.

> What was the problem with that?

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=btdu -> misses `aarch64` entry. Adding it ...  to have `arch=('aarch64' 'i686' 'x86_64')`  makes it fail to resolve dtools. 

retrieving https://github.com/archlinux/svntogit-community/blob/master/dtools/trunk/PKGBUILD and altering the `arch` line to contain `arch=('aarch64' 'x86_64')` results in missing dependencies `dmd` and `libphobos`

retrieving `dmd`  from https://github.com/archlinux/svntogit-community/blob/master/dmdtrunk/ seems to first workout, but since 'aarch64' is missing, a pgp for that would fail. So I tried ` makepkg -si --skippgpcheck` which would result in 

```
object.Exception@compiler/src/build.d(1706): Cannot figure 32/64 model from "aarch64
"
----------------
??:? [0xaaaab9b45aeb]
??:? [0xaaaab9b6e00f]
??:? [0xaaaab9b4f9ff]
compiler/src/build.d:1706 [0xaaaab9ad7433]
compiler/src/build.d:1208 [0xaaaab9ad2883]
compiler/src/build.d:152 [0xaaaab9ad1113]
compiler/src/build.d:63 [0xaaaab9ad0d5f]
??:? [0xaaaab9b4f6a7]
??:? [0xaaaab9b4f587]
??:? [0xaaaab9b4f3ef]
??:? [0xffff64b57b7f]
??:? __libc_start_main [0xffff64b57c5f]
<unknown dir>/<unknown file>:81 [0xaaaab9ad022f]
==> ERROR: A failure occurred in build().
    Aborting...
```

At that point, I started to grab your binary.

**Comment by CyberShadow** [comment]
DMD can only target x86 and x86_64. ALARM should package `dtools` but change the `dmd`/`libphobos` dependencies with `d-runtime` / `d-stdlib` (maybe gated to some version range). This should pull in `ldc` which I think should build on aarch64.

Or maybe ALARM has some other LDC-based package that provides `dtools`?

Also if that doesn't work, `dtools` isn't a hard dependency, I think it's only needed for the `--rdmd` build mode, so I would also just try without it.

**Comment by zDEFz** [comment]
Tried without `--rdmd` no luck. Tried without `dtools` no luck.

But the first 3 lines tell all I need to know:
```
Error Failed to invoke the compiler /usr/bin/gdc to determine the build platform: Using built-in specs.
COLLECT_GCC=/usr/bin/gdc
Target: aarch64-unknown-linux-gnu
```

ARCHLINUX on the M chips is not officially supported from ARCHLINUX itself, but we do care, thats why its a thing in the first place. This appears to be something more complicated. Do you wish to take some of the communication through IRC? Might be easier for you. I'm on "Libera Chat" and "OFTC". You can reach me on the alias "bluetail".

**Comment by CyberShadow** [comment]
OK, let's continue there.

**Comment by CyberShadow** [comment]
> [arch-pkg@thecybershadow.net](mailto:arch-pkg@thecybershadow.net): TLS is required, but was not offered by host

Fixed

> https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=btdu -> misses `aarch64` entry.

Fixed: https://aur.archlinux.org/cgit/aur.git/commit/?h=btdu&id=00bf7cd17dad7a380f52a2b6953617575ba3daa1

> Trying to get dtools... but its not on the `alarm` repo

Fixed: https://github.com/archlinuxarm/PKGBUILDs/pull/1987

The btdu AUR PKGBUILD now builds on my phone. Great success?

Thank you for your help on this!
