### ISSUE TITLE
Mounting top-level subvolume example and risk?

### ISSUE THREAD

**Issue by patrickwolf** [CyberShadow/btdu#18]
BTDU requires to mount the top-level subvolume (-o subvol=/,subvolid=5).

My environment is a Synology raid.

And so I'm wondering:

1. What is the bash command to mount the top-level subvolume (read-only)
2. Considering that child subvolumes are already mounted separately, is there any risk of corruption to mounting the top level one (as the child ones are inside of/beneath it)?
3. Could you consider adding the reply to the official help file so others can find out quicker?

Thanks a lot!.

**Comment by CyberShadow** [comment]
> What is the bash command to mount the top-level subvolume (read-only)

btdu should print an example of this command when you try to run it against a non-top-level subvolume. To also mount it read-only, add `ro` to the list of options (e.g. `-o ro,subvol=...`).

> Considering that child subvolumes are already mounted separately, is there any risk of corruption to mounting the top level one (as the child ones are inside of/beneath it)?

No.

Note that you can even mount the same filesystem (btrfs or non-btrfs) multiple times on multiple mount points, or different filesystems on the same mount point (the most recent mount is the one which is visible), or the same subvolume multiple times, or the same subvolume as many times recursively as you want within each other.

If the operating system manages mount points, it might get confused by any filesystems mounted by hand, but I would guess that this would be very unlikely to lead to data loss. If you have any concerns about this, I suggest that you consult with the operating system's documentation or community on how to temporarily mount filesystems in a way that does not interfere with the operating system.

> Could you consider adding the reply to the official help file so others can find out quicker?

Certainly, though so far I don't see anything that would be valuable to add. Both questions are in the domain of general Linux knowledge, and the second seems to be a personal concern (which I hope I've addressed).

**Comment by patrickwolf** [comment]
Thank you that helped a lot. When dealing with 120TB of production data the concern if double mounting could be risky feels serious. So I did it now and it worked fine and BTDU is very helpful. Thank you!
