### ISSUE TITLE
How to track if files are deduplicated?

### ISSUE THREAD

**Issue by patrickwolf** [CyberShadow/btdu#19]
Let's say I copy the **same** 10MB file from an external device to BTRFS into **two** folders.
- tmp\a\10mb.dat - Exclusive 10mb
- tmp\b\10mb.dat - Exclusive 10mb
- tmp\                    - Exclusive 20mb

Now I create a snapshot and I get (as they share space with the snapshot):
- tmp\a\10mb.dat - Exclusive 0mb
- tmp\b\10mb.dat - Exclusive 0mb
- tmp\                    - Exclusive 0mb - Shared 20mb

This isn't helpful to know what are debup candidates. So I'm wondering can BTDU help me here to see that a & b are not deduplicated (without deleting all snapshots)?

So that I can see this after a dedup with ie cp --reflink=always I get (with and without snapshot)
- tmp\a\10mb.dat - Exclusive 0mb
- tmp\b\10mb.dat - Exclusive 0mb
- tmp\                    - Exclusive 0mb - Shared 10mb

**Comment by CyberShadow** [comment]
I can think of two ways:

- Look at the representative size to check if both `a/10mb.dat` and `b/10mb.dat` have non-zero size. If they both have non-zero representative size, that means they are not deduplicated. If only one has non-zero representative size, that means they are deduplicated. (If they both have zero representative size, you are looking at a non-representative path for the files, and will need to find the representative path of `a/10mb.dat`).
- Look at what other paths `a/10mb.dat` shares data with. You can do this by descending into the file. If you see `b/10mb.dat` in the list, then they are mutually deduplicated.

If btdu ever gains a feature which restricts its view to some path within the filesystem, that could be used to discard samples outside that path, making the "exclusive size" usable for this purpose.

**Comment by patrickwolf** [comment]
Thank you. I'm still pondering how to apply your answer as I have 500K+ files :) 

Seems like the only practical way i have right now is to delete all snapshots and then see which files are using exclusive space. Agreed?

**Comment by CyberShadow** [comment]
I can't answer with certainty without knowing the relationship between these files and the deduplication goal, but generally I suspect that the above two methods would still apply if you examine the contents of the lexicographically smallest snapshot. I would not look at exclusive size in this situation.
