### ISSUE TITLE
Build Error on Debian 10. 

### ISSUE THREAD

**Issue by ChojinDSL** [CyberShadow/btdu#2]
I'm trying to build this from source on Debian 10 (Buster). Am I missing a dependency?

I'm getting the following error when trying to build with `dub build -b release`

```
Performing "release" build using /usr/bin/ldc2 for x86_64.
ncurses 0.0.149: target for configuration "minimal" is up to date.
btdu 0.2.1: building configuration "application"...
source/btdu/browser.d(24,8): Error: module `locale` is in file 'core/sys/posix/locale.d' which cannot be read
import path[0] = source/
import path[1] = /root/.dub/packages/ae-0.0.2833
import path[2] = /root/.dub/packages/btrfs-0.0.11/btrfs/src/
import path[3] = /root/.dub/packages/ncurses-0.0.149/ncurses/source/
import path[4] = /usr/lib/ldc/x86_64-linux-gnu/include/d/ldc
import path[5] = /usr/lib/ldc/x86_64-linux-gnu/include/d
import path[6] = /usr/include/d
/usr/bin/ldc2 failed with exit code 1.
```

My locale is set to:

```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by CyberShadow** [comment]
Unfortunately, your D compiler is too old.

If you are using DMD or LDC, please make sure you have a more recent version.

If you are using GDC (gcc with D support), you will need to use a different D compiler. The D version that GDC implements is too old.

https://dlang.org/download.html has some options.

**Comment by CyberShadow** [comment]
For reference, [the relevant module was added to D](https://github.com/dlang/druntime/pull/2789#event-2621253778) on 2019-09-10. The first LDC version containing this module [was released](https://forum.dlang.org/post/bqgjkqwwytrjyqdsoltt@forum.dlang.org) in 2019-12-20.

The initial release of Debian Buster was on 2019-07-06, so I'm guessing they are not updating their packaged version of LDC.

**Comment by ChojinDSL** [comment]
Thanks.
