### ISSUE TITLE
"Status bar" (samples and resolution) does not appear anymore after ed368d5

### ISSUE THREAD

**Issue by intelfx** [CyberShadow/btdu#20]
### synopsis
It appears ed368d5 introduced a regression. The "status bar" with the sample count and approximate resolution does not show for me anymore.

### environment
Arch, GNOME Terminal + tmux

#### working
![working](https://user-images.githubusercontent.com/1158172/229255213-1645aaf5-0835-4994-ba67-b593c26e385c.png)

#### regressed
![regressed](https://user-images.githubusercontent.com/1158172/229255599-8d82f901-ef33-478b-9fe9-52bd50e2d4ab.png)

**Comment by CyberShadow** [comment]
Thanks for the report. It was due to a compatibility hack which worked around a bug, but was not removed when that bug was fixed.
