### ISSUE TITLE
Misreported used size by btdu in pyshical mode (maybe)

### ISSUE THREAD

**Issue by alemoh1234** [CyberShadow/btdu#21]
I may be interpreting this data wrong, but it seems I may have found a bug in physical mode.

While the unallocated space and metadata(duplicated) show correctly, once I enter /SINGLE/DATA and start navigating my files, some of them show the wrong space used (much less than what the actual file takes up), and the free space (UNUSED) is wildly wrong. 

Obs: my BTRFS install is a simple one, automatically done by manjaro in a single SSD.

Here are some commands output:

BTDU in -p mode:

```
btdu v0.5.0 @ /mnt/sda2                                                                                                                                      [PAUSED] 
--- /<SINGLE>/<DATA> --------------------------------------------------------------------------------------------------------------------------------------------------
  ~11.82 GiB [#         ]  <NO_INODE>                                                                                                                                  
  ~71.00 GiB [##########]  <UNUSED>
  ~21.00 GiB [##        ] /@
  ~4.756 GiB [          ] /@cache
  ~66.99 GiB [######### ] /@home
  ~2.037 GiB [          ] /@log
  ~4.491 GiB [          ] /timeshift-btrfs

--- Details: ----------------------------------------------------------------------------------------------------------------------------------------------------------
- Full path: /mnt/sda2
- Average query duration: 0.0002491 seconds
- Represented size: ~182.1 GiB (306451 samples), ±242.6 MiB
- Logical offsets: ..., 185807908152, 67499195313, 26414524317
- Physical offsets: ..., 1:336123374904, 1:68564548529, 1:25332393885`
```
BTDU in normal mode:
```
btdu v0.5.0 @ /mnt/sda2                                                                                                                                      [PAUSED] 
--- /<SINGLE>/<DATA> --------------------------------------------------------------------------------------------------------------------------------------------------
  ~19.84 GiB [##        ]  <NO_INODE>                                                                                                                                  
  ~19.38 GiB [#         ]  <UNUSED>
  ~27.50 GiB [##        ] /@
  ~7.785 GiB [          ] /@cache
  ~98.93 GiB [##########] /@home
  ~2.399 GiB [          ] /@log
  ~6.113 GiB [          ] /timeshift-btrfs

--- Details: ----------------------------------------------------------------------------------------------------------------------------------------------------------
- Full path: /mnt/sda2
- Average query duration: 0.0002802 seconds
- Represented size: ~182.0 GiB (276869 samples), ±102.6 MiB
- Logical offsets: ..., 227972342342, 98740561859, 78583809087
```

And `sudo btrfs fi usage /`:

```
Overall:
    Device size:                 210.53GiB
    Device allocated:            190.02GiB
    Device unallocated:           20.50GiB
    Device missing:                  0.00B
    Device slack:                  3.50KiB
    Used:                        167.52GiB
    Free (estimated):             39.77GiB      (min: 29.52GiB)
    Free (statfs, df):            39.77GiB
    Data ratio:                       1.00
    Metadata ratio:                   2.00
    Global reserve:              387.14MiB      (used: 0.00B)
    Multiple profiles:                  no

Data,single: Size:182.01GiB, Used:162.74GiB (89.41%)
   /dev/sda2     182.01GiB

Metadata,DUP: Size:4.00GiB, Used:2.39GiB (59.74%)
   /dev/sda2       8.00GiB

System,DUP: Size:8.00MiB, Used:48.00KiB (0.59%)
   /dev/sda2      16.00MiB

Unallocated:
   /dev/sda2      20.50GiB
```

I'am also having an issue with NO_INODE [link to my reddit post](https://www.reddit.com/r/btrfs/comments/132wtxm/free_space_missing_please_read/), but it is unrelated to this finding. (of course, if you know how to solve this please do tell me, I'am only commenting about this in this issue in case the NO_INODE part is somehow related to this).

**Comment by CyberShadow** [comment]
That indeed looks bizarre.

One possible explanation which might produce results such as these could be that a balance was running while btdu was collecting information in the physical mode. btdu only reads the device tree at start-up; if some chunks were unmapped while btdu was running, that could show up as a lot of `<UNUSED>` space. So perhaps check `sudo btrfs balance status /`?

**Comment by alemoh1234** [comment]
Unfortunately I got the same results like 5 different times (in a 30-hour time frame), where I'am sure balance was not running (mainly because I ran balance manually 3 different times and had to check with the command you supplied to know when it finished).

As of right now:

`sudo btrfs balance status /`:
`No balance found on '/'`

and `sudo btdu -p --max-time 20s /mnt/sda2`:
` btdu v0.5.0 @ /mnt/sda2                                                                                                                                      [PAUSED] 
--- /<SINGLE>/<DATA> --------------------------------------------------------------------------------------------------------------------------------------------------
  ~11.82 GiB [#         ]  <NO_INODE>                                                                                                                                  
  ~70.85 GiB [##########]  <UNUSED>
  ~21.00 GiB [##        ] /@
  ~4.769 GiB [          ] /@cache
  ~67.11 GiB [######### ] /@home
  ~2.032 GiB [          ] /@log
  ~4.510 GiB [          ] /timeshift-btrfs

--- Details: ----------------------------------------------------------------------------------------------------------------------------------------------------------
- Full path: /mnt/sda2
- Average query duration: 0.0002400 seconds
- Represented size: ~182.1 GiB (320144 samples), ±237.4 MiB
- Logical offsets: ..., 67873961515, 166825847610, 4879993452
- Physical offsets: ..., 1:68939314731, 1:313920088890, 1:3797863020`

**Comment by CyberShadow** [comment]
Thanks! I think I found a bug in btdu which can produce such results. Could you try https://github.com/cybershadow/btdu/commit/e7dd686 ([artifacts](https://github.com/CyberShadow/btdu/actions/runs/4843307492#artifacts))?

**Comment by alemoh1234** [comment]
Perfect! issue solved, now everything shows up as expected (if only solving my NO_INODE issue was this simple hahaha)
BTDU `e7dd686` in -p mode:
```
 btdu v0.5.0 @ /mnt/sda2                                                                                                                                      [PAUSED] 
--- /<SINGLE>/<DATA> --------------------------------------------------------------------------------------------------------------------------------------------------
  ~19.87 GiB [##        ]  <NO_INODE>
  ~19.15 GiB [#         ]  <UNUSED>
  ~27.74 GiB [##        ] /@
  ~7.868 GiB [          ] /@cache
  ~99.21 GiB [##########] /@home                                                                                                                                       
  ~2.264 GiB [          ] /@log
  ~6.039 GiB [          ] /timeshift-btrfs

--- Details: ----------------------------------------------------------------------------------------------------------------------------------------------------------
- Full path: /mnt/sda2
- Average query duration: 0.0003343 seconds
- Represented size: ~182.1 GiB (232678 samples), ±278.3 MiB
- Logical offsets: ..., 149536795280, 100367756017, 315585741972
- Physical offsets: ..., 1:140955249296, 1:99302402801, 1:169565242516
```
