### ISSUE TITLE
Also release an ARMv7 version as well

### ISSUE THREAD

**Issue by 05storm26** [CyberShadow/btdu#22]
For those who still use an older raspberry this would be useful.

**Comment by CyberShadow** [comment]
OK, but the ultimate solution would be to get your distribution to package it. Please file a packaging request with your distribution! :)

**Comment by CyberShadow** [comment]
That's a new one... could be an instance of https://github.com/cybershadow/d-btrfs/commit/b5496165ff03309a8089923e3dcb930fad17057b or the struct layout being actually incorrect due to padding, need to look at this closer.

**Comment by CyberShadow** [comment]
@05storm26 Could you try the artifact from https://github.com/CyberShadow/btdu/actions/runs/5071526913

**Comment by CyberShadow** [comment]
The links work for me, please try again.

**Comment by 05storm26** [comment]
Yeah, you are right. I have tried it on my `Raspberry Pi 3 Model B Rev 1.2`. It seems to work correctly.

![Screenshot from 2023-05-29 20-09-54](https://github.com/CyberShadow/btdu/assets/8590289/603471d7-6d38-4926-9a73-262bbc9a5396)

 Could you add this binary to the releases from this point on?
Currently I think debian has an issue with packaging `dub`  stuff:

> [Dub](https://github.com/dlang/dub/), D's package manager, can not be used for Debian packaging at time, as it lacks ways to find locally installed source copies, writes into $HOME at build-time, does not install binaries and does not handle dependencies on C libraries well. It is recommended to use the [Meson](https://packages.debian.org/sid/devel/meson) build system or Automake/CMake for D code instead.
https://wiki.debian.org/D

So providing compiled binaries for all the most popular platforms is probably doubly important, because users might not have a btrdu package for a while.

**Comment by CyberShadow** [comment]
> Could you add this binary to the releases from this point on?

OK

> Currently I think debian has an issue with packaging `dub` stuff:

No, that's just an outdated pile of bull.

- Debian already has software written in D packaged.
- Cargo, npm, pip, etc. all have the same qualities.
- https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=btdu shows how btdu can be packaged without problems, even with stricter (self-imposed) constraints.

> So providing compiled binaries for all the most popular platforms is probably doubly important, because users might not have a btrdu package for a while.

No, you have it backwards. Software distributions like Debian exist to solve software distribution problems. It's just that no one has packaged btdu yet.

**Comment by 05storm26** [comment]
Okay, well, hopefully it will make it to the distros then, shortly. Thanks for providing the artifacts.

**Comment by CyberShadow** [comment]
It's not going to happen until more users demand it. If you want it to happen, do your part and let the distro know that you want them to package software you want packaged :)

As I stated on the RFP, I'm happy to help with packaging and work with the distributions to make it happen, but I don't want to maintain packages for twenty distributions for every project I maintain all on my own.
