### ISSUE TITLE
How to get Checksum from releases

### ISSUE THREAD

**Issue by esp13** [CyberShadow/btdu#27]
Hi,

I love you work (thank you again),
How can we verify the checksum of a binary file downloaded from your repo?
I usually I download the file, do a sha256sum locally and compare the result with the site were I downloaded it.

**Comment by CyberShadow** [comment]
Currently I do not have anything set up that generates first-party checksums. Well, the build is done on GitHub Actions, so, GitHub is the first party. But we could make it also output some `.sha256sum` artifacts, if that makes sense?

**Comment by esp13** [comment]
I think yes if we can download/display the sha256 checksum for each file :)
