### ISSUE TITLE
Error when trying to import with v0.5.1

### ISSUE THREAD

**Issue by esp13** [CyberShadow/btdu#28]
Hi,

When I try to import a file previously exported with **btdu v0.5.1** I get this error:
`Fatal error: Can't parse string: bool should be case-insensitive 'true' or 'false'`

Export:
`./btdu-static-x86_64-v0.5.1 /mnt/btrfsroot/ --minresolution=50000000 --headless --export=btduexport`

Import:
`./btdu-static-x86_64-v0.5.1 --import=btduexport`

I'm on linux Mint 21.1 running the last x86_64 release downloaded from your github (without compiling it)

**Comment by CyberShadow** [comment]
Can you try with master, please?

**Comment by CyberShadow** [comment]
I believe this problem should be fixed on master, please post a comment or reopen if not.
