### ISSUE TITLE
How to actually use this tool?

### ISSUE THREAD

**Issue by edwinclement08** [CyberShadow/btdu#33]
Am i doing something fundamentally wrong??

Version: btdu v0.5.1

![image](https://github.com/user-attachments/assets/c46bbff5-c27d-46ee-9647-7c2220b7309e)

More Info if needed
![image](https://github.com/user-attachments/assets/e9b546eb-aca5-49a5-81e2-2ac5c749c28a)
![image](https://github.com/user-attachments/assets/ae911455-3a21-4728-bb2f-5a841956cd9f)

**Comment by CyberShadow** [comment]
Hi, sorry, did you try reading the message that btdu prints and following the suggestion there?

**Comment by edwinclement08** [comment]
It's mounted as a root partition, so can I only do this from a Live CD?

**Comment by CyberShadow** [comment]
No. You can mount it multiple times. The instructions show you how to do that.

**Comment by edwinclement08** [comment]
Oh cool, it works that way. It was not very clear for me, personally. Maybe the error message can be written with less jargon.
