### ISSUE TITLE
Ehancement suggestion : Add export/import functionnality ?

### ISSUE THREAD

**Issue by esp13** [CyberShadow/btdu#7]
Hello,

I like the export/import ability of ncdu, I export the scans of drives so I can quickly search what is taking space without plugging the drive or launching a new scan.

I wonder if it could be possible to do the same with btdu for btrfs?
It would maybe be harder to set because there are extra steps : let the scan running to wanted size level then press "p" key and "enter" key.

**Comment by CyberShadow** [comment]
Thanks for the suggestion. I've been thinking about some kind of import/export functionality.

Would you mind elaborating in a bit more detail of how you use the ncdu feature? Do you run it in headless mode to collect results on one machine, and then view them on another?

**Comment by CyberShadow** [comment]
OK, here's an initial implementation: https://github.com/CyberShadow/btdu/compare/next

It should be comparable with ncdu's, though btdu can't *read* saved results from standard input.

**Comment by CyberShadow** [comment]
Fixed build and binaries: https://github.com/CyberShadow/btdu/actions/runs/1838747535

**Comment by esp13** [comment]
Nice :)

I get a "floating point exception" is there a way to add debug output? I tried the -v and --verbose option without success.

**Comment by CyberShadow** [comment]
What do you do to get it?

You'd need a debug build for a useful stack trace...

**Comment by esp13** [comment]
I think it was my fault I didn't put the last "/" on btrfs filesystem path:

`./btdu-static-x86_64 --export=/outputpath/test.btdu --headless --minresolution=500 mnt_btrfs2`

With this it seems running: 
`./btdu-static-x86_64 --export=/outputpath/test.btdu --headless --minresolution=500 mnt_btrfs2/`

**Comment by esp13** [comment]
It works great, thank you much :)

I changed min resolution to 500 000 (500KB)

I tried 
`./btdu-static-x86_64 --expert --export=/outputpath/test.btdu --headless --minresolution=500000 mnt_btrfs2/ | gzip > test.btdu.gz`
but this doesn't work

**Comment by CyberShadow** [comment]
> I tried
> `./btdu-static-x86_64 --expert --export=/outputpath/test.btdu --headless --minresolution=500000 mnt_btrfs2/ | gzip > test.btdu.gz`
> but this doesn't work

Maybe try `--export=o` (or `-o-`), like ncdu?

**Comment by esp13** [comment]
> Maybe try --export=- (or -o-), like ncdu?

Yes this works :)
`./btdu-static-x86_64 --expert -o- --headless --minresolution=500000 mnt_btrfs2/ | gzip > test.btdu.gz`

But how to import? I tried : 
`zcat test.btdu.gz | ./btdu-static-x86_64 -f-`
=> Unrecognized option -
or
`zcat test.btdu.gz | ./btdu-static-x86_64 -f`
=> No path specified

**Comment by CyberShadow** [comment]
It's not possible to import from standard input at the moment. The data must be in a real file.

**Comment by esp13** [comment]
ok :+1:

**Comment by esp13** [comment]
Off topic question:

I had to mount the btrfs path with:

`mount /dev/mapper/vercacrypt ~/mntbtrfs/ -o subvolid=5`

Is there a way to run the scan from a deeper folder level of the btrfs volume?

**Comment by CyberShadow** [comment]
No, it's not possible (due to how the algorithm works). See second item in "It differs from classic analyzers through the following properties:" in the README.

**Comment by esp13** [comment]
oups sorry :grimacing: :innocent:

**Comment by esp13** [comment]
Second off topic question:

with ncdu you can display (and sort by) modification date when using -e option
Is there a way to do the same with btdu? Is there something like the `--expert `option that about [readme](https://github.com/CyberShadow/btdu/blob/master/CONCEPTS.md#size-metrics) (:stuck_out_tongue_winking_eye: ) collect more metrics about size but for date?

**Comment by CyberShadow** [comment]
No, the API we use does not give btdu this information. It would have to perform one more filesystem call using a completely different API to obtain it.

**Comment by CyberShadow** [comment]
I'm closing this issue as the feature has been implemented but feel free to post any additional feedback or questions.
