### ISSUE TITLE
Btrfs as Root Filesystem

### ISSUE THREAD

**Issue by mritzmann** [CyberShadow/btdu#8]
Hi! 

I installed the latest version of `btdu` as follows.

```shell
wget https://github.com/CyberShadow/btdu/releases/download/v0.3.1/btdu-static-x86_64
mv btdu-static-x86_64 btdu
chmod +x btdu
```

However, during execution the following error occurs.

```shell
$ ./btdu /
Fatal error: / is not the root btrfs subvolume - please specify the path to a mountpoint mounted with subvol=/ or subvolid=5
E.g.: mkdir /tmp/sda2 && mount -o subvol=/ /dev/sda2 /tmp/sda2 && ./btdu /tmp/sda2

$ ./btdu /dev/sda2       
Fatal error: /dev/sda2 is not a btrfs filesystem

$ ./btdu /@rootfs 
Fatal error: open (No such file or directory)

$ ./btdu /\@rootfs
Fatal error: open (No such file or directory)
```

In my case Btrfs is mounted as root partition.

```shell
$ cat /etc/fstab | grep btrfs
UUID=2080d58a-d1b3-4bc7-bd8d-67662935e96a /               btrfs   defaults,space_cache=v2,subvol=@rootfs 0       0

$ df -Th -t btrfs    
Filesystem     Type   Size  Used Avail Use% Mounted on
/dev/sda2      btrfs  9.8T   50G  9.8T   1% /

$ mount | grep btrfs | grep -v docker
/dev/sda2 on / type btrfs (rw,relatime,space_cache=v2,subvolid=256,subvol=/@rootfs)

$ findmnt -nt btrfs | grep -v docker
/                                       /dev/sda2[/@rootfs]                                      btrfs  rw,relatime,space_cache=v2,subvolid=256,subvol=/@rootfs
```

I am not sure: am I doing something wrong or is this a false positive?

Thanks,
Markus

**Comment by CyberShadow** [comment]
Same confusion as in #3.

Your `/` (root filesystem, i.e. where the distribution is installed) is located on the `/@rootfs` subvolume, which is not the btrfs root subvolume. The btrfs root subvolume would be `subvolid=5,subvol=/`.

Please follow the instructions printed by btdu.

**Comment by CyberShadow** [comment]
Hi @mritzmann,

Thanks for filing this issue.

As I mentioned above the problem is due to some confusing terminology about what "root" means in various contexts.

Hopefully this is now cleared up. I will improve the message that btdu prints in this circumstance, which should hopefully guide more users in the future towards understanding the situation.

**Comment by mritzmann** [comment]
Ahh, got it! Thank you for your support.

**Comment by mritzmann** [comment]
And thanks for this change https://github.com/CyberShadow/btdu/commit/01dc14b27666340c916d331ceb482cbc78f6ca4c, I think this will help others who have the same understanding problem in the future.
