### ISSUE TITLE
What does <ERROR> mean?

### ISSUE THREAD

**Issue by Samisafool** [CyberShadow/btdu#9]
![image](https://user-images.githubusercontent.com/59611020/169757878-738c6831-04ea-4874-9edd-548f9c70c3bd.png)

**Comment by Samisafool** [comment]
After `sudo btrfs balance start -dusage=66 /` it dropped very much, down to 1.2gb

**Comment by Samisafool** [comment]
Nevermind, I missed the explanation somehow

**Comment by CyberShadow** [comment]
Hi, I'm curious, did you find this project via aconfmgr somehow, or independently?

Also, I should really make it not show ENOENT as errors. The explanation is a clumsy workaround.

**Comment by Samisafool** [comment]
> did you find this project via aconfmgr somehow

Yes. I visited your profile a while ago when you said you had a lot of other projects (in an aconfmgr issue) and found this. handy tool, btw!
